### PR TITLE
A bluetooth peer should not be treated as unreachable if the device isn't connected to a network.

### PR DESCRIPTION
**Pull request by Happy0**
See https://gitlab.com/staltz/manyverse/issues/342 for more details

### CODE REVIEW

**Comment by staltz** [comment]
Thanks @Happy0 this makes total sense. However, since you're here, I'd like to discuss a related corner case. With this commit https://github.com/staltz/ssb-legacy-conn/commit/09c99b9c63d52cfdba4765feaa95a39cc5b62c05 I had to turn off bluetooth peers stored in the gossip table, because it was causing a crash in the android app. After a long while debugging, I learned that it happened because OS Bluetooth was turned off, but this plugin attempted to connect to such bluetooth address upon plugin initialization. I wish I could show you a stacktrace or log of the crash, but actually this time the crash was silent, it just informed something very low level regarding the C code (it was a SIGSEGV), no Java or JS stack trace. But I'm quite sure it was a bluetooth connection because the if condition `&& data.source !== 'bt'` fixed it.

**Comment by Happy0** [comment]
@staltz - huh, interesting. I can't reproduce this, but since it's such a low level exception (SIGSEGV) it could be some subtlety about us running different hardware / android versions or whatever.

Could you do me a big favour when you have the time, and reproduce it for me again but turn on debug logging for the `ssb-mobile-bluetooth-manager` module (`process.env['DEBUG'] = "*" at the top of `index.js` in manyverse is the easiest way to do it, and perhaps pipe the full logcat out to a file so that I can see the log statements from the Java based classes too? e.g. `adb logcat | tee output.txt`

I do have guards in the connection code against IOExceptions and stuff (which would occur if bluetooth isn't enabled or the peer isn't reachable), but maybe I could try adding an explicit 'is bluetooth enabled' guard? I'll publish a new version with that and let you try it (when you have time) :).

**Comment by staltz** [comment]
I caught a stack trace (see below). I used ssb-legacy-conn 1.0.13 which uses this PR, and additionally, I removed the `&& data.source !== 'bt'` from the if condition. I got the stack trace below by doing this:

- Start Manyverse on phone A and B, both with empty databases
- Write a few posts on both A and B
- Sync them together with Bluetooth (only, no other mode on)
- Close the app on both phones
- Open Manyverse on phone A only (not phone B)
- Within ~4 seconds the app crashes (I assume because it tried to connect with something that was on the gossip table)

```
03-11 16:39:15.342   623   643 D BluetoothManagerService: Message: 20
03-11 16:39:15.342   623   643 D BluetoothManagerService: Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@e64ad8:true
03-11 16:39:15.348 14685 14718 W Java7Support: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
03-11 16:39:15.376 14685 14718 D bluetooth_bridge: Outgoing connections thread. Sock path: /data/user/0/se.manyver/files/manyverse_bt_outgoing.sock
03-11 16:39:15.376 14685 14726 D bt_control_socket: connecting to control socket
03-11 16:39:15.376 14685 14718 D listen_incoming: Registering receiver for bluetooth being enabled / disabled
03-11 16:39:15.377 14685 14726 W System.err: java.io.IOException: Connection refused
03-11 16:39:15.377 14685 14726 W System.err: 	at android.net.LocalSocketImpl.connectLocal(Native Method)
03-11 16:39:15.377 14685 14726 W System.err: 	at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:292)
03-11 16:39:15.378 14685 14726 W System.err: 	at android.net.LocalSocket.connect(LocalSocket.java:131)
03-11 16:39:15.378 14685 14726 W System.err: 	at com.scuttlebutt.bluetoothbridge.control.ControlUnixSocket.establishConnection(ControlUnixSocket.java:293)
03-11 16:39:15.378 14685 14726 W System.err: 	at com.scuttlebutt.bluetoothbridge.control.ControlUnixSocket.access$000(ControlUnixSocket.java:27)
03-11 16:39:15.378 14685 14726 W System.err: 	at com.scuttlebutt.bluetoothbridge.control.ControlUnixSocket$1.run(ControlUnixSocket.java:107)
03-11 16:39:15.378 14685 14726 W System.err: 	at java.lang.Thread.run(Thread.java:761)
03-11 16:39:15.378 14685 14726 D bt_control_socket: Error establishing connection to control socket: Connection refused retries remaining: 10
03-11 16:39:15.510 14685 14718 D ReactNative: Initializing React Xplat Bridge.
03-11 16:39:15.514 14685 14718 D ReactNative: Initializing React Xplat Bridge before initializeBridge
03-11 16:39:15.529 14685 14718 D ReactNative: Initializing React Xplat Bridge after initializeBridge
03-11 16:39:15.529 14685 14718 D ReactNative: CatalystInstanceImpl.runJSBundle()
03-11 16:39:15.552 14685 14732 D ReactNative: ReactInstanceManager.setupReactContext()
03-11 16:39:15.553 14685 14732 D ReactNative: CatalystInstanceImpl.initialize()
03-11 16:39:15.598 14738 14738 W Thread-5: type=1400 audit(0.0:24): avc: denied { ioctl } for path="/sys/kernel/debug/tracing/trace_marker" dev="debugfs" ino=2168 ioctlcmd=5451 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:debugfs_trace_marker:s0 tclass=file permissive=0
03-11 16:39:15.598 14738 14738 W Thread-5: type=1400 audit(0.0:25): avc: denied { ioctl } for path="socket:[54105]" dev="sockfs" ino=54105 ioctlcmd=5451 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:surfaceflinger:s0 tclass=unix_stream_socket permissive=0
03-11 16:39:17.472 14685 14685 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
03-11 16:39:17.494 14685 14685 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
03-11 16:39:17.586 14685 14731 I ReactNativeJS: Running application "Manyverse.Central" with appParams: {"initialProps":{"componentId":"Component5"},"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
03-11 16:39:17.597 14685 14696 I art     : Do partial code cache collection, code=27KB, data=30KB
03-11 16:39:17.597 14685 14696 I art     : After code cache collection, code=27KB, data=30KB
03-11 16:39:17.597 14685 14696 I art     : Increasing code cache capacity to 128KB
03-11 16:39:17.841   232   470 D audio_hw_primary: out_standby: enter: stream (0xb623d740) usecase(1: low-latency-playback)
03-11 16:39:17.877   232   470 I tfa9887 : tfa9887_power: Set amplifier power to 0
03-11 16:39:18.614 14685 14731 I ReactNativeJS: Running application "Manyverse.Drawer" with appParams: {"initialProps":{"componentId":"Component3"},"rootTag":11}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
03-11 16:39:19.271 14685 14696 I art     : Do partial code cache collection, code=57KB, data=62KB
03-11 16:39:19.272 14685 14696 I art     : After code cache collection, code=54KB, data=59KB
03-11 16:39:19.272 14685 14696 I art     : Increasing code cache capacity to 256KB
03-11 16:39:20.392 14738 14738 W Thread-5: type=1400 audit(0.0:26): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
03-11 16:39:23.246 14685 14740 E NODEJS-MOBILE: ssb-friends: stream legacy api used
03-11 16:39:23.499   623  1913 D GraphicsStats: Buffer count: 7
03-11 16:39:23.499   623   635 I WindowManager: WIN DEATH: Window{9c95bec u0 se.manyver/se.manyver.MainActivity}
03-11 16:39:23.500   623  1913 I ActivityManager: Process se.manyver (pid 14685) has died
03-11 16:39:23.500   623  1913 D ActivityManager: cleanUpApplicationRecord -- 14685
03-11 16:39:23.501   623  1913 W ActivityManager: Force removing ActivityRecord{371778e u0 se.manyver/.MainActivity t454}: app died, no saved state
03-11 16:39:23.506   231   231 I Zygote  : Process 14685 exited cleanly (1)
```

**Comment by staltz** [comment]
Here's another logcat, this time with `process.env['DEBUG']='*'` in `src/backend/index`, there isn't that much useful info about the crash though:

```
03-11 16:49:12.662   623   918 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=se.manyver/.MainActivity (has extras)} from uid 10031 on display 0
03-11 16:49:12.670   232   470 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
03-11 16:49:12.671   232   470 D audio_hw_primary: start_output_stream: enter: stream(0xb623d740)usecase(1: low-latency-playback) devices(0x2)
03-11 16:49:12.671   232   470 D audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: )
03-11 16:49:12.671   232   470 I msm8960_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(15)
03-11 16:49:12.672   232   470 I tfa9887 : tfa9887_power: Set amplifier power to 1
03-11 16:49:12.672   232   470 D audio_hw_primary: select_devices: done
03-11 16:49:12.760   623   914 I ActivityManager: Start proc 15081:se.manyver/u0a139 for activity se.manyver/.MainActivity
03-11 16:49:12.979 15081 15081 I ACRA    : ACRA is enabled for se.manyver, initializing...
03-11 16:49:13.011 15081 15081 V fb-UnpackingSoSource: locked dso store /data/user/0/se.manyver/lib-main
03-11 16:49:13.012 15081 15081 V fb-UnpackingSoSource: deps mismatch on deps store: regenerating
03-11 16:49:13.012 15081 15081 V fb-UnpackingSoSource: so store dirty: regenerating
03-11 16:49:13.180 15081 15081 D ApkSoSource: not allowing consideration of lib/armeabi-v7a/libc++_shared.so: deferring to libdir
03-11 16:49:13.180 15081 15081 D ApkSoSource: not allowing consideration of lib/armeabi-v7a/libfb.so: deferring to libdir
03-11 16:49:13.180 15081 15081 D ApkSoSource: not allowing consideration of lib/armeabi-v7a/libfolly_json.so: deferring to libdir
03-11 16:49:13.180 15081 15081 D ApkSoSource: not allowing consideration of lib/armeabi-v7a/libgifimage.so: deferring to libdir
03-11 16:49:13.180 15081 15081 D ApkSoSource: not allowing consideration of lib/armeabi-v7a/libglog.so: deferring to libdir
03-11 16:49:13.180 15081 15081 D ApkSoSource: not allowing consideration of lib/armeabi-v7a/libglog_init.so: deferring to libdir
03-11 16:49:13.181 15081 15081 D ApkSoSource: not allowing consideration of lib/armeabi-v7a/libgnustl_shared.so: deferring to libdir
03-11 16:49:13.181 15081 15081 D ApkSoSource: not allowing consideration of lib/armeabi-v7a/libicu_common.so: deferring to libdir
03-11 16:49:13.181 15081 15081 D ApkSoSource: not allowing consideration of lib/armeabi-v7a/libimagepipeline.so: deferring to libdir
03-11 16:49:13.181 15081 15081 D ApkSoSource: not allowing consideration of lib/armeabi-v7a/libjsc.so: deferring to libdir
03-11 16:49:13.182 15081 15081 D ApkSoSource: not allowing consideration of lib/armeabi-v7a/libnode.so: deferring to libdir
03-11 16:49:13.182 15081 15081 D ApkSoSource: not allowing consideration of lib/armeabi-v7a/libnodejs-mobile-react-native-native-lib.so: deferring to libdir
03-11 16:49:13.182 15081 15081 D ApkSoSource: not allowing consideration of lib/armeabi-v7a/libprivatedata.so: deferring to libdir
03-11 16:49:13.182 15081 15081 D ApkSoSource: not allowing consideration of lib/armeabi-v7a/libreactnativejni.so: deferring to libdir
03-11 16:49:13.182 15081 15081 D ApkSoSource: not allowing consideration of lib/armeabi-v7a/libucrop.so: deferring to libdir
03-11 16:49:13.183 15081 15081 D ApkSoSource: not allowing consideration of lib/armeabi-v7a/libyoga.so: deferring to libdir
03-11 16:49:13.183 15081 15081 V fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
03-11 16:49:13.184 15081 15081 V fb-UnpackingSoSource: starting syncer worker
03-11 16:49:13.216 15081 15081 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/se.manyver/lib-main (from syncer thread)
03-11 16:49:13.216 15081 15081 V fb-UnpackingSoSource: not releasing dso store lock for /data/user/0/se.manyver/lib-main (syncer thread started)
03-11 16:49:13.220 15081 15081 D ReactNative: ReactInstanceManager.ctor()
03-11 16:49:13.244 15081 15081 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
03-11 16:49:13.290 15081 15081 D ReactNative: ReactInstanceManager.createReactContextInBackground()
03-11 16:49:13.290 15081 15081 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
03-11 16:49:13.290 15081 15081 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
03-11 16:49:13.290 15081 15081 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
03-11 16:49:13.290 15081 15081 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
03-11 16:49:13.331 15081 15107 I art     : Thread[12,tid=15107,Native,Thread*=0xaa43dd00,peer=0x12d689d0,"Thread-2"] recursive attempt to load library "/data/app/se.manyver-2/lib/arm/libfb.so"
03-11 16:49:13.333 15081 15107 D ReactNative: ReactInstanceManager.createReactContext()
03-11 16:49:13.351 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.reactnativenavigation.react.ElementViewManager
03-11 16:49:13.364 15081 15108 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
03-11 16:49:13.380 15081 15108 I OpenGLRenderer: Initialized EGL, version 1.4
03-11 16:49:13.380 15081 15108 D OpenGLRenderer: Swap behavior 1
03-11 16:49:13.400 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
03-11 16:49:13.414 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupViewManager
03-11 16:49:13.415 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
03-11 16:49:13.418 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeViewManager
03-11 16:49:13.419 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
03-11 16:49:13.421 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextViewManager
03-11 16:49:13.422 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
03-11 16:49:13.425 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.checkbox.ReactCheckBoxManager
03-11 16:49:13.428 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
03-11 16:49:13.432 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
03-11 16:49:13.437 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
03-11 16:49:13.439 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
03-11 16:49:13.451 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
03-11 16:49:13.452 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
03-11 16:49:13.453   623   644 I ActivityManager: Displayed se.manyver/.MainActivity: +721ms
03-11 16:49:13.460 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
03-11 16:49:13.462 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
03-11 16:49:13.470 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
03-11 16:49:13.476 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
03-11 16:49:13.477 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
03-11 16:49:13.481 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
03-11 16:49:13.482 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
03-11 16:49:13.488 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
03-11 16:49:13.496 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
03-11 16:49:13.501 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
03-11 16:49:13.502 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
03-11 16:49:13.504 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
03-11 16:49:13.505 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
03-11 16:49:13.510 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
03-11 16:49:13.517 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
03-11 16:49:13.520 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
03-11 16:49:13.521 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
03-11 16:49:13.522 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextShadowNode
03-11 16:49:13.526 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
03-11 16:49:13.538 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
03-11 16:49:13.545 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
03-11 16:49:13.550 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
03-11 16:49:13.551 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
03-11 16:49:13.561 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
03-11 16:49:13.566 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
03-11 16:49:13.566 15081 15107 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
03-11 16:49:13.603 15081 15107 D NetworkSecurityConfig: No Network Security Config specified, using platform default
03-11 16:49:13.611   623   643 D BluetoothManagerService: Message: 20
03-11 16:49:13.611   623   643 D BluetoothManagerService: Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@895ff6:true
03-11 16:49:13.618 15081 15107 W Java7Support: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
03-11 16:49:13.647 15081 15107 D bluetooth_bridge: Outgoing connections thread. Sock path: /data/user/0/se.manyver/files/manyverse_bt_outgoing.sock
03-11 16:49:13.647 15081 15127 D bt_control_socket: connecting to control socket
03-11 16:49:13.648 15081 15107 D listen_incoming: Registering receiver for bluetooth being enabled / disabled
03-11 16:49:13.648 15081 15127 W System.err: java.io.IOException: Connection refused
03-11 16:49:13.649 15081 15127 W System.err: 	at android.net.LocalSocketImpl.connectLocal(Native Method)
03-11 16:49:13.649 15081 15127 W System.err: 	at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:292)
03-11 16:49:13.649 15081 15127 W System.err: 	at android.net.LocalSocket.connect(LocalSocket.java:131)
03-11 16:49:13.649 15081 15127 W System.err: 	at com.scuttlebutt.bluetoothbridge.control.ControlUnixSocket.establishConnection(ControlUnixSocket.java:293)
03-11 16:49:13.649 15081 15127 W System.err: 	at com.scuttlebutt.bluetoothbridge.control.ControlUnixSocket.access$000(ControlUnixSocket.java:27)
03-11 16:49:13.649 15081 15127 W System.err: 	at com.scuttlebutt.bluetoothbridge.control.ControlUnixSocket$1.run(ControlUnixSocket.java:107)
03-11 16:49:13.649 15081 15127 W System.err: 	at java.lang.Thread.run(Thread.java:761)
03-11 16:49:13.649 15081 15127 D bt_control_socket: Error establishing connection to control socket: Connection refused retries remaining: 10
03-11 16:49:13.791 15081 15135 D NODEJS-RN: Node assets copy using pre-built lists
03-11 16:49:13.793 15081 15107 D ReactNative: Initializing React Xplat Bridge.
03-11 16:49:13.796 15081 15107 D ReactNative: Initializing React Xplat Bridge before initializeBridge
03-11 16:49:13.812 15081 15107 D ReactNative: Initializing React Xplat Bridge after initializeBridge
03-11 16:49:13.812 15081 15107 D ReactNative: CatalystInstanceImpl.runJSBundle()
03-11 16:49:13.835 15081 15138 D ReactNative: ReactInstanceManager.setupReactContext()
03-11 16:49:13.835 15081 15138 D ReactNative: CatalystInstanceImpl.initialize()
03-11 16:49:14.710 15081 15135 V NODEJS-RN: Building folder hierarchy for nodejs-native-assets-armeabi-v7a
03-11 16:49:14.713 15081 15135 V NODEJS-RN: Copying assets using file list for nodejs-native-assets-armeabi-v7a
03-11 16:49:15.519 15081 15135 D NODEJS-RN: Node assets copy completed successfully
03-11 16:49:15.513 15141 15141 W Thread-6: type=1400 audit(0.0:27): avc: denied { ioctl } for path="/sys/kernel/debug/tracing/trace_marker" dev="debugfs" ino=2168 ioctlcmd=5451 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:debugfs_trace_marker:s0 tclass=file permissive=0
03-11 16:49:15.513 15141 15141 W Thread-6: type=1400 audit(0.0:28): avc: denied { ioctl } for path="socket:[59748]" dev="sockfs" ino=59748 ioctlcmd=5451 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:surfaceflinger:s0 tclass=unix_stream_socket permissive=0
03-11 16:49:15.842   232   470 D audio_hw_primary: out_standby: enter: stream (0xb623d740) usecase(1: low-latency-playback)
03-11 16:49:15.856 15081 15081 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
03-11 16:49:15.879   232   470 I tfa9887 : tfa9887_power: Set amplifier power to 0
03-11 16:49:15.881 15081 15081 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
03-11 16:49:15.893 15081 15091 I art     : Do partial code cache collection, code=24KB, data=30KB
03-11 16:49:15.893 15081 15091 I art     : After code cache collection, code=24KB, data=30KB
03-11 16:49:15.893 15081 15091 I art     : Increasing code cache capacity to 128KB
03-11 16:49:15.940 15081 15137 I ReactNativeJS: Running application "Manyverse.Central" with appParams: {"initialProps":{"componentId":"Component5"},"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
03-11 16:49:16.949 15081 15137 I ReactNativeJS: Running application "Manyverse.Drawer" with appParams: {"initialProps":{"componentId":"Component3"},"rootTag":11}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
03-11 16:49:17.525 15081 15091 I art     : Do partial code cache collection, code=56KB, data=62KB
03-11 16:49:17.526 15081 15091 I art     : After code cache collection, code=52KB, data=58KB
03-11 16:49:17.526 15081 15091 I art     : Increasing code cache capacity to 256KB
03-11 16:49:20.488 15141 15141 W Thread-6: type=1400 audit(0.0:29): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
03-11 16:49:23.215 15081 15173 E NODEJS-MOBILE: ssb-friends: stream legacy api used
03-11 16:49:23.502   623   987 D GraphicsStats: Buffer count: 7
03-11 16:49:23.502   623  1483 I WindowManager: WIN DEATH: Window{e22bb2a u0 se.manyver/se.manyver.MainActivity}
03-11 16:49:23.502   623   987 I ActivityManager: Process se.manyver (pid 15081) has died
03-11 16:49:23.502   623   987 D ActivityManager: cleanUpApplicationRecord -- 15081
03-11 16:49:23.503   623   987 W ActivityManager: Force removing ActivityRecord{fbaa99c u0 se.manyver/.MainActivity t455}: app died, no saved state
03-11 16:49:23.515   231   231 I Zygote  : Process 15081 exited cleanly (1)
```

Device: HTC One, Android 7.1.1 (actually LineageOS 14.1-20170302)

**Comment by staltz** [comment]
Also I ran it the other way around (phone B alone, instead of phone A alone), and got pretty similar logcat, no point in pasting it. Phone B was: Google Nexus 5, Android 6.0.1 (Android Stock).

**Comment by Happy0** [comment]
That "03-11 16:39:15.377 14685 14726 W System.err: java.io.IOException: Connection refused" exception is actually benign - that's a Java thread trying to establish the Unix socket but the nodejs process hasn't started it yet, so it sleeps a few seconds retries up to 10 times - I get that in my logs too.

Are those  full logs? Or is that filtering stuff out with 'grep'?

**Comment by staltz** [comment]
Those are the full logs, unfortunately. It was simply `adb logcat`. 8-|

**Comment by Happy0** [comment]
@staltz - thanks. how odd!

I just published `react-native-bluetooth-socket-bridge` version 1.1.1 which does an explicit check for the enabledness of bluetooth before trying to connect. would you mind trying with that version?

**Comment by Happy0** [comment]
Sorry, I mean version ` 1.1.2`

**Comment by staltz** [comment]
@Happy0 Just for your feedback, I merged your PR and updated react-native-bluetooth-socket-bridge, and this crash still happens.

**Comment by Happy0** [comment]
Thanks @staltz - I'll try and reproduce it and get to the bottom of it =]

**Comment by staltz** [comment]
Also, I messed up putting this discussion here. It's obviously an issue that should be in Manyverse :D

**Comment by Happy0** [comment]
Haha! :D.

I've been able to reproduce the bug (it seems to happen regardless of
whether Bluetooth is enabled or not.)

Oddly, it seems to explode long before it gets anywhere near attempting a
Bluetooth connection. It seems to happen somewhere in the middle of the
gossip code :S.

The SIGABORT error and log entries imply the OS thinks the UI thread is
blocked.

I wonder if the gossip code goes into an infinite loop or something. I'll
keep digging...

Feel free to move this discussion to another issue :p

**Comment by staltz** [comment]
Let's move the discussion back here: https://gitlab.com/staltz/manyverse/issues/342

**Pull request merged**
